### ISSUE TITLE
Error running call reference function for resource esx_addonaccount: 

### ISSUE THREAD

**Issue by ddh3** [FXServer-ESX/fxserver-esx_addonaccount#1]
[   1722671] Error running call reference function for resource esx_addonaccount: server/classes/addonaccount.lua:11: attempt to perform arithmetic on a nil value (local 'm')
[   1722671] stack traceback:
[   1722671] 	server/classes/addonaccount.lua:11: in local 'ref'
[   1722671] 	citizen:/scripting/lua/scheduler.lua:277: in function <citizen:/scripting/lua/scheduler.lua:268>
[   1722671] 	[C]: in function 'coroutine.resume'
[   1722671] 	citizen:/scripting/lua/scheduler.lua:33: in field 'CreateThreadNow'
[   1722671] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
[   1722687] Error running call reference function for resource esx_jobs: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
[   1722687] stack traceback:
[   1722687] 	[C]: in function 'error'
[   1722703] 	citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
[   1722703] 	citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
[   1722703] 	citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
[   1722703] 	citizen:/scripting/lua/scheduler.lua:338: in field 'addMoney'
[   1722703] 	server/esx_jobs_sv.lua:12: in local 'ref'
[   1722703] 	citizen:/scripting/lua/scheduler.lua:277: in function <citizen:/scripting/lua/scheduler.lua:268>
[   1722703] 	[C]: in function 'coroutine.resume'
[   1722703] 	citizen:/scripting/lua/scheduler.lua:33: in field 'CreateThreadNow'
[   1722703] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
[   1722718] Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
[   1722718] stack traceback:
[   1722718] 	[C]: in function 'error'
[   1722718] 	citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
[   1722718] 	citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
[   1722718] 	citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
[   1722718] 	citizen:/scripting/lua/scheduler.lua:338: in local 'cb'
[   1722718] 	server/main.lua:81: in upvalue 'handler'
[   1722718] 	citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
[   1722718] stack traceback:
[   1722718] 	[C]: in function 'error'
[   1722718] 	citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
[   1722718] 	citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by indilo53** [comment]
When you do what exactly ?

**Comment by ddh3** [comment]
This happens when you exit the server.
